language: php
php:
  - '5.6'
env:
  - TEST_DIR=lib
script: cd $TEST_DIR &&
        printf "\n" | pecl install zmq-beta &&  
        echo "extension=zmq.so" >> /etc/php5/cli/php.ini && 
        composer install
